project_id = "ofgifhuyzwymgcvrhszu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.register-user]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.manage-user]
verify_jwt = false